### ISSUE TITLE
Why are blocks being read & deserialized twice?

### ISSUE THREAD

**Issue by dpc** [RCasatta/blocks_iterator#34]
In [`read_detect`](https://github.com/RCasatta/blocks_iterator/blob/da0489c242404da43572d0e01f281d32e56404ea/src/read_detect.rs#L141) it seems like you already have a deserialized block, and then you throw it away and return `File` and offsets outside to have to read and deserialize it again later. Why not just return that `block` out?

**Comment by dpc** [comment]
And then I don't understand why the first `next` from a list of possible next hashes is arbitrarily picked. https://github.com/RCasatta/blocks_iterator/blob/da0489c242404da43572d0e01f281d32e56404ea/src/reorder.rs#L140

**Comment by RCasatta** [comment]
> In [`read_detect`](https://github.com/RCasatta/blocks_iterator/blob/da0489c242404da43572d0e01f281d32e56404ea/src/read_detect.rs#L141) it seems like you already have a deserialized block, and then you throw it away and return `File` and offsets outside to have to read and deserialize it again later. Why not just return that `block` out?

The reason is to have lower and more predictable memory usage. Previous versions was working by putting directly `Block` in the reorder `HashMap` but resulting in even thousands of blocks kept in memory. I would like this to work with low memory so I accepted the tradeoff of reading from disk twice. I would be in favor of having both the options (reading twice or putting the parsed block in the HashMap) via a configuration parameter

> And then I don't understand why the first `next` from a list of possible next hashes is arbitrarily picked.
> 
> https://github.com/RCasatta/blocks_iterator/blob/da0489c242404da43572d0e01f281d32e56404ea/src/reorder.rs#L140

Here the error is that `BlockExtra` next field is still a vec while it should be a single element.
As said before there wasn't `FsBlock` before, and it was just `BlockExtra`. During parsing of blocks, the next field is filled, and since there could be reorgs there could be more than one block following during reordering, but when enough successors in one path are found only one is kept as you can see here
https://github.com/RCasatta/blocks_iterator/blob/master/src/reorder.rs#L83

**Comment by dpc** [comment]
> The reason is to have lower and more predictable memory usage. Previous versions was working by putting directly Block in the reorder HashMap but resulting in even thousands of blocks kept in memory.

Aren't blocks 99.9% of the time in order already in bllkxxx files? The whole thing seems like rather heavy pessimization. Instead, I would convert the code to return all blocks serially (`flat_map` it, instead of batches like it currently does) , always use channel sizes of `0` (because otherwise they are just buffer-float) and this way there will ever be only few blocks decoded in-flight at the time. 

I still don't understand how exactly `reorder` works, but the way I think about it: mainnet has very shallow reorgs, so one only needs ~5MB of memory for 5 blocks in-flight. Testnet might have larger reorgs, but blocks there are significantly tinnier so probably comes out to a similar 5MB-10MB value.

Even it was a problem, I would rather throw away decoded `Block` only when it's actually needed (blocks are being queued, and some count of total backloged txes go above a certain threshold), than throw that work altogether every time.

Again - I don't yet understand `reorder`, but it looks fairly complex, so maybe it's giving guarantees that I don't yet understand or something.

In implementation for reorgs I had, I can assume the the later block is always "more current" (became part of the active chain later) than any previous one, so I only need to keep track of one list of `max_reorg` blocks in one sequence (in a map keyed by height). Whenever new block comes, I check its `previous_hash` againt the `hash` of the currently buffered highest block. If they don't match I know there's a reorg, and I remove the highest buffered block and repeat until I effectively truncated the buffer enough. When the buffer length is equal `max_reorg`, that means the lowest height block can no longer be reorged. Notably it merges all overlapping reorgs to help keep memory usage low. This seems simpler and don't require tracking and checking "followers" at all. (Well, actually in `rust-bitcoin-indexer` I push reorg handling on the consumer and return buffered blocks immediately, and only track their hashes to detect reorg for safety reason, but what I described is the same, just delays returning blocks so the consumer doesn't have to take care of it).

**Comment by dpc** [comment]
Oh dear. I had time to finally sit down and think about it again, and it occurred to me that in `rust-bitcoin-indexer` this scheme is slightly different than what I described and works because the code is free to start asking again for lower block heights again. The way `reorder` step works is not the same, so it can't just throw the (possibly temporarily) orphaned blocks. So I guess I know now why the additional tracking of things is necessary.

I guess only the idea of preserving the block when possible is applicable.

**Comment by RCasatta** [comment]
> Aren't blocks 99.9% of the time in order already in bllkxxx files?
 
Not at all.
That's what I thought also, but they aren't out of order only because of reorgs (rare as one would expect) but because blocks are downloaded in parallel during IBD

**Comment by dpc** [comment]
Oh, I see.

BTW. I wonder how well would downloading blocks via p2p protocol (pointed a the local node) work in comparison to jsonrpc & blk files, and then how well would a hybrid approach work: get the headers in parallel via p2p to know the active chain upfront.

**Comment by RCasatta** [comment]
I know Electrs switched to P2P to request blocks, maybe @romanz could tell us something about that

**Comment by RCasatta** [comment]
https://github.com/RCasatta/blocks_iterator/issues/22#issuecomment-1031443486
