### ISSUE TITLE
Get a `block_extra` or a `block` from a `Txid`, a `TxOut` or an `OutPoint`

### ISSUE THREAD

**Issue by gawlk** [RCasatta/blocks_iterator#74]
Hi !

First of all, thank you for your hard work ! Your crate is exactly what I was looking to play around and crunch the data from my node.

I've been trying to get previous blocks linked to a block via a txout/outpoint (or any other data inside the block) but I'm having a quite a hard time with this. For context, the goal is to do it for each outpoint of each block.

While browsing the library's code, I couldn't find any way to do this.

Am I missing something and there is an idiomatic way to do it ?

**Comment by gawlk** [comment]
Thank you ! But sadly neither `tx_fee` nor `outpoint_values` will do.

Just for context, what I'm currently trying to do is fetch the timestamp (this is why I said I needed the block) of each `TxOut` in `outpoint_values` of every single `block_extra`.

I'll check what I can do with bitcoin core thanks ! But I'll need something super fast, if it's too slow I was thinking maybe creating another RocksDB just for that ?

**Comment by RCasatta** [comment]
Do you have low-memory requirement for your task?
The memory mode (the default if no db directory is specified) stores the utxo set in about 5gb of memory, I guess you can store what you need in memory with similar requirement using an
`HashMap<Outpoint,u32>`
Inserting values for every output value in a block and removing them for every input

**Comment by gawlk** [comment]
I actually did something very similar and forgot update and close this issue.

Thank you so much though, you've been very helpful !
