### ISSUE TITLE
Your experiences with redb?

### ISSUE THREAD

**Issue by dpc** [RCasatta/blocks_iterator#80]
I really dislike `rocksdb` for being in C++, which complicates all sorts of things in Rust project, and noticed that `redb` is at 1.x . Do you happen to have any (especially negative) thoughts about it?

**Comment by RCasatta** [comment]
My feedback is related to pre 1.x versions of redb

The API looks great, but the performance does not match rocksdb in particular for writes. In blocks_iterator testing they are worse than the benchmarks shown in the redb home page.

Also, the space used is more in redb than rocksdb with the same data.

[Here](https://github.com/cberner/redb/issues/532) some tweaks the maintainer gave me to improve things a bit

**Comment by dpc** [comment]
Thanks. Much appreciated.

**Comment by dpc** [comment]
@RCasatta So I take it as flushing periodically brings the performance close to rocksdb?

**Comment by RCasatta** [comment]
Closer but still sensibly slower writes IIRC
