### ISSUE TITLE
Reorder map too large error

### ISSUE THREAD

**Issue by AdamISZ** [RCasatta/blocks_iterator#83]
Hi Riccardo,
thanks for the tool.

I'm encountering an error where the hardcoded 10000 value [here](https://github.com/RCasatta/blocks_iterator/blob/b421617cba76a6a5c119fa5733c6c8181b2c7483/src/stages/reorder.rs#L138) is not large enough.

```
...
...
00000000000000000004338497075326553447f2e8a1d78a8ca589c3236ac1f9 [0x0000000000000000000599d496bbfaf18df312c0afda8f56027531059553d678]
next: 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
thread '<unnamed>' panicked at /home/ekaggata/.cargo/git/checkouts/blocks_iterator-94aa1dab5349f4be/b421617/src/stages/reorder.rs:144:37:
Reorder map grow more than 10000
```

This is just a first draft (copied the basic format from your example), but for debug you'll doubtless want to know what the code is, so:

```rust
#![allow(non_snake_case)]

/*
Tool to write public keys from raw blocks
for curve tree construction.
 */

use blocks_iterator::PeriodCounter;
use env_logger::Env;
use blocks_iterator::log::info;
use std::error::Error;
use std::fs::File;
use std::io::Write;
use itertools::Itertools;
use std::time::Duration;
//use structopt::StructOpt;

fn main() -> Result<(), Box<dyn Error>> {
    // TODO this tool is derived from
    // https://github.com/RCasatta/blocks_iterator/blob/b421617cba76a6a5c119fa5733c6c8181b2c7483/examples/outputs_versions.rs
    // as a starting point.
    // The command line handling has been ignored for now,
    // we will add this (and possibly options in the config file)
    // for filenames, blocks file source, and probably output encodings.
    env_logger::Builder::from_env(Env::default().default_filter_or("info")).init();
    info!("start");
    let mut period = PeriodCounter::new(Duration::from_secs(10));

    //let mut config = Config::from_args();
    let mut config = blocks_iterator::Config::new(
        "/home/waxwing/.bitcoin/blocks", bitcoin::Network::Bitcoin);
    config.start_at_height = 733000;
    config.stop_at_height = Some(834000);
    config.skip_prevout = true;
    let iter = blocks_iterator::iter(config);
    let mut output_file = File::create("keysfound.txt").unwrap();
    for block_extra in iter {
        if period.period_elapsed().is_some() {
            info!(
                "# {:7} {}",
                block_extra.height, block_extra.block_hash
            );
        }

        if block_extra.height == 481824 {
            info!("segwit locked in");
        }
        if block_extra.height == 687456 {
            info!("taproot locked in");
        }
        let mut v: Vec<String> = Vec::new();
        for (_txid, tx) in block_extra.iter_tx() {
            for (_i, output) in tx.output.iter().enumerate() {
                if output.script_pubkey.is_witness_program() {
                    let version = output.script_pubkey.as_bytes()[0] as usize;
                    if version == 0x51 {
                        // lose version byte and also leading 0x20 (length)
                        let buf1 = &output.script_pubkey.as_bytes()[2..];
                        let towrite = hex::encode(buf1);
                        v.push(towrite);
                    }
                }
            }
        }
        let fullstr = v.into_iter().unique().join(" ");
        write!(output_file, "{}", fullstr).expect("Failed to write keys to file.");

    }
    Ok(())
}
```

**Comment by dpc** [comment]
I didn't even look at the code, but possibly the reordering should not be happening unless if the `getblockcount` on the new chain tip is not heigher the the currently processed height. That would prevent truncation from messing things up.

**Comment by AdamISZ** [comment]
My best guess for now is that, looking at reorder.rs, it indeed is failing to find blocks connecting to the genesis hash and failing for that reason - and, if I want to use the tool with a pruned block DB, I'll need to fork the project and hack in a fake genesis hash (starting from a point above the pruned height), although I could be wrong in both senses - that could fail to work, and also maybe I'm missing something and it's not necessary.

One thing I could be missing is - shouldn't it find the block *headers* and therefore hashes, fine, even though it's pruned? Hmm.

**Comment by RCasatta** [comment]
Hi @AdamISZ 
I didn't put any effort in handling pruned data...

> One thing I could be missing is - shouldn't it find the block headers and therefore hashes, fine, even though it's pruned? Hmm.

This means that with pruning core keeps the headers bytes in the blocks*.dat files while removing the block transactions ?

**Comment by AdamISZ** [comment]
> This means that with pruning core keeps the headers bytes in the blocks*.dat files while removing the block transactions ?

No, it seems not unfortunately ... the earlier \*.dat files just aren't there.

**Comment by AdamISZ** [comment]
@RCasatta does it sound feasible to hardcode a different value for genesis block hash in there (i.e. thinking about https://github.com/RCasatta/blocks_iterator/blob/master/src/stages/reorder.rs#L102 )? Would the code in `reorder.rs` just follow the same logic with a new starting block? Or would that not work for some reason?

**Comment by RCasatta** [comment]
It makes sense to change that to achieve what you want, it could work but I am not sure.
If it works, it may make sense to provide it via config params to support pruned nodes

**Comment by AdamISZ** [comment]
Fwiw the following rather horrifying hack "works":

```rust
let bin_bh: [u8; 32] = hex::FromHex::from_hex("deadbeef...").unwrap();
let mut next = BlockHash::from_raw_hash(sha256d::Hash::from_byte_array(bin_bh));
```

(replacing the above linked definition of `next` ; of course you have to add the `use` statement: `use bitcoin::hashes::{hex, sha256d, Hash};`)

... where `deabeef..` is the big-endian encoding of a block hash. But "works" with caveats:

* the block hash used there should be that of the *first* block in your database, identifiable with `bitcoin-cli getblockchaininfo` (but I guess it changes over time, so you need to have bitcoind not running)
* defining `start_height` and `end_height` doesn't work (at least, in my test), because I think with this hack it treats your first block as literally block 1 (or 0, whatever).

Still, it does output the data I wanted from a filter, so, it (barely) passes the bar of at least being worth reporting.

**Comment by RCasatta** [comment]
Happy that you found a way to achieve what you needed. 

I opened an [issue](https://github.com/RCasatta/blocks_iterator/issues/84) for pruned node support and I am going to close this.
