### ISSUE TITLE
migrate to clap

### ISSUE THREAD

**Issue by king-11** [RCasatta/blocks_iterator#89]
given the [structopt](https://github.com/TeXitoi/structopt) library is in maintenance mode and itself suggests to make the [migration](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating-1)

**Comment by king-11** [comment]
it might also be a good idea to maybe just move the `main.rs` into a different crate in repository to enable flags on it so that it the library doesn't pull up dependencies required just for binary.

**Comment by RCasatta** [comment]
Concept ack on both changes.
I don't plan to work on this in the near future

**Comment by king-11** [comment]
I can take this up would be glad to contribute

**Comment by king-11** [comment]
is it fine if we move the `main.rs` file into examples? That will make these three optional:
- structopt -> replace by clap
- env_logger

**Comment by king-11** [comment]
Sure I think I am aligned with both the suggestions:
- move `main.rs` into `cli` crate
- feature gate `Config` parsing

**Comment by king-11** [comment]
Just one more confirmation these would be two new crates so would the name be
- blocks_iterator (lib)
- blocks_iterator_cli (main)

Should the examples still lie in lib crate or they can be moved as well?

**Comment by RCasatta** [comment]
Ack for the names, not sure for the examples honestly, whatever you think it's more appropriate.
